apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernates-example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernates-example
    spec:
      containers:
        - name: kubernates-example
          image: gcr.io/citric-lead-272713/kubernates_example
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kubernates-example-service
  labels:
    name: kubernates-example-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kubernates-example
  type: LoadBalancer